### ISSUE TITLE
Add 𝜏

### ISSUE THREAD

**Issue by jpmhouston** [hyperjeff/Physical#4]
Rationale: https://tauday.com/tau-manifesto

**Comment by hyperjeff** [comment]
I believe the Physical framework does one step better. This system makes the opinionated choice that angles are not dimensionless, as measured in radians or otherwise. 1 revolution (or 1 cycle) both do the job that the τ Manifesto suggests for τ, while dealing with the units correctly. I see the τ Manifesto as just missing its mark, even though I agree with much of its analysis, but the enemy isn't π, it's treating angles as dimensionless.

Just to be sure, I'll take the time to read thru it more to make sure there isn't something about it i've missed. Thanks for the comment, and feel free to disagree.
